config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' , registrations: 'users/registrations'}
  devise_scope :user do
    get 'profile', to: 'users/registrations#profile', as: 'profile'
    get 'users/:id/show', to: 'users/registrations#show', as: 'show'
    post 'vote', to: 'users/registrations#vote', as: 'vote'
  end
  root 'pages#index'

  get "/products/watches", to: "products#index_watches"
  get "/products/bags", to: "products#index_bags"
  get "/products/jewelry", to: "products#index_jewelry"
  resources :products , except: :index
  get "/home", to: "pages#index"

  resources :orders, only: [:new, :create, :index, :destroy]
  resources :products
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base

  CATEGORIES = ['watches', 'jewelry', 'bags']


  has_many  :orders
  belongs_to :user
end

=begin
Other way to do it via as enum
  as_enum :category, watches: 2, jewelry: 1, bags: 0
product = Product.new
product.category = :jewelry
product.jewelry?

=end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :products # User to product is 1 to N relationship
  has_many :orders # User to orders is 1 to N relationship
  devise   :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable,
           :omniauthable, omniauth_providers: [:facebook]
           # besides the original device attributes, we add these for making our model omniauthable
           #for FB login:



  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :add_allow_credentials_headers

  def add_allow_credentials_headers
  # https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#section_5
  #
  # Because we want our front-end to send cookies to allow the API to be authenticated
  # (using 'withCredentials' in the XMLHttpRequest), we need to add some headers so
  # the browser will not reject the response
    response.headers['Access-Control-Allow-Origin'] = request.headers['Origin'] || '*'
    response.headers['Access-Control-Allow-Credentials'] = 'true'
  end

  def options
    head :status => 200, :'Access-Control-Allow-Headers' => 'accept, content-type'
  end

end

app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def index
    #set @orders to the current_user's orders only
    @orders = Order.where(renter_id: current_user.id)
  end


  def new
    @order = Order.new
  end

  def create
   @order = Order.new(order_params)
   @order.renter_id = current_user.id
   @order.product_id = order_params[:product_id]
   #assign product.owner_id to order.owner_id
   if @order.save
     flash[:notice] = 'your order was created'
     redirect_to root_path
   else
     flash[:notice] = 'Oops something went wrong'
     render 'new'
   end
  end

  def destroy
    Order.find(params[:id]).destroy
    flash[:success] = "item deleted"
    redirect_to orders_path
  end

 private

 def order_params
  params.require(:order).permit(:delivery_date, :return_date, :product_id)
 end

 def set_order

 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only:[:show, :index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]

 def new
   @product = Product.new
 end

 def index
    @products = Product.all
 end

  def index_watches
    @products = Product.where(category: "watch")
  end

 def index_bags
    @products = Product.where(category: "bags")
 end

  def index_jewelry
    @products = Product.where(category: "jewelry")
  end

 def show
   @product = Product.find(params[:id])
   @order = Order.new
 end

 def create
   @product = Product.new(product_params)
   if @product.save
     flash[:notice] = 'your product was created'
     redirect_to products_path
   else
     flash[:notice] = 'Oops something went wrong'
     render 'new'
   end
 end

 private

 def product_params
  params.require(:product).permit(:title, :category, :description, :brand, :user_id, :price, :gender)
 end

 def set_product
 end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def profile

  end

  def show
    @user = User.find(params[:id])
  end

  def vote
    @rated_user = User.find(params[:user_id])
    @rated_user.renter_number_ratings = params[:score]
    @rated_user.save
    redirect_to request.referer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_controller_helper.rb
module OmniauthCallbacksControllerHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prestige</title>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700', rel: 'stylesheet' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
</body>
</html>

app/views/orders/index.html.erb
  <!-- user the @orders to display them in a nice way -->
<div class="bg-white">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <H1>Product Details</H1>
        <div class="social-box">
          <% @orders.each do |order| %>
          <h2><%= order.product.title %></h2>
          <%= image_tag order.product.picture_path %>
          <form action="">
          <%=link_to "delete order", order_path(order), method: :delete %>
          </form>
          <% end %>
          <%= link_to "to the product", orders_path, class: "btn btn-primary" %>
        </div>
      </div>
      <div class="col-xs-8">
      </div>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<!-- TODO create a order form -->
<div class="container">
 <div class="row">
     <%= form_for @order do |f| %>
      Delivery date:    <%= f.date_select :delivery_date %>
    </br>
      Return date:   <%= f.date_select :return_date %>
    </br>
        <%= f.submit %>
     <% end %>
 </div>
</div>


<br>

app/views/orders/show.html.erb
<div class="container">
 <div class="row">
    <div class="col-lg-12">
      <H1>See all products</H1>
    </div>
    <div class="col-lg-5 text-background">
      <h2><%= @order.title %></h2>
      <p> <%=order.renter_id%></p>
       <p> <%=order.owner_id%></p>
       <p> <%=order.product_id%> </p>
       <p> <%=order.rent_cost%></p>
       <p> <%=order.freight_cost%></p>
       <p><%=order.submission_date%></p>
       <p><%=order.delivery_date%></p>
       <p><%=order.return_date%></p>
       <p><%=order.finalreception_date%></p>
       <p><%=order.origin_city%></p>
       <p><%=order.origin_country%></p>
       <p><%=order.detination_city%></p>
       <p><%=order.destination_country%></p>
      <br>
      <%= link_to "to the order", order_path(@order), class: "btn btn-primary" %>
    </div>

    <div class="col-lg-1">
    </div>

    <div>
      <%= image_tag product.picture_path %>

    </div>
 </div>
</div>

app/views/pages/index.html.erb
 <div class="video">
  <iframe id="vimeo_player" class="vimeo"
 src="//player.vimeo.com/video/43934591?title=0&amp;byline=0&amp;portrait=0&amp;color=3a6774&amp;autoplay=1&amp;loop=1&amp;background=1"
 width="960" height="540" frameborder="0" webkitallowfullscreen
 mozallowfullscreen allowfullscreen></iframe>
 <div class="overlay">
   <div class="container">
    <div class="redbar"></div>
      <h1>Rent luxury goods from special owners</h1>
      <div>
        <small></small>
      </div>
      <div>
        <button class="btn btn-primary">RENT NOW !</button>
      </div>
    </div>
 </div>
</div>

<div class="bg-white">
  <div class="container">
    <div class="image-menu">
      <div class="row">

        <div class="col-xs-4 no-padding" >
          <div class="frontpage" style="background-image: url(<%= image_url('necklacesDark.png') %>)">
            <!-- your list of social links -->
            <%= link_to products_jewelry_url  do %>

            <h3 class="tumbheading">JEWELRY</h3>

            <% end %>
          </div>
        </div>


        <div class="col-xs-4 no-padding" >
          <div class="frontpage" style="background-image: url(<%= image_url('BagsDark.png') %>)" >
            <!-- your list of social links -->
            <%= link_to products_bags_path do %>

            <h3 class="tumbheading">BAGS</h3>


            <% end %>
          </div>
        </div>

        <div class="col-xs-4 no-padding" >
          <div class="frontpage" style="background-image: url(<%= image_url('watchesDark.png') %>)" >
            <!-- your list of social links -->
            <%= link_to products_watches_path  do %>

            <h3 class="tumbheading">WATCHES</h3>


            <% end %>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>
<section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>About</h2>
                    <hr class="star-light">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-lg-offset-2">
                    <p>At Prestige, you can rent beautiful luxury goods from an unlimited selection of special owners willing to rent them out for a special occasion.</p>
                </div>
                <div class="col-lg-4">
                    <p>Do you have luxury goods? Why don't you rent them out and make some profits to buy new ones or to get extra cash? Become a renter on Prestige now!</p>
                </div>
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <a href="#" class="btn btn-lg btn-outline">

                    </a>
                </div>
            </div>
        </div>
    </section>

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<footer>
    <div class="footer" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">
                    <h3> Find us at</h3>
                    <ul class="social">
                        <li> <a href="#"> <i class=" fa fa-facebook">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-twitter">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-google-plus">   </i> </a> </li>
                    </ul>
                </div>
            </div>
            <!--/.row-->
        </div>
        <!--/.container-->
    </div>
    <!--/.footer-->

    <div class="footer-bottom">
        <div class="container">
            <p class="pull-left"> Copyright © LorenzVillain. All right reserved. </p>
        </div>
    </div>
    <!--/.footer-bottom-->
</footer>

app/views/products/index.html.erb
<!-- Here I show all my products of x category -->

<div class="container">
 <div class="row">

   <div class="col-lg-12">
   <H1>See all products</H1>
    </div>

   <% @products.each do |product| %>

     <div class="col-lg-5 text-background">
       <h2><%= product.category %></h2>
       <p> title: <%= product.title%></p>
       <p> description: <%= product.description%></p>
       <p> brand: <%= product.brand%> </p>
       <p> price: <%= product.price%> € </p>
      <!-- for later <p> gender: <%= product.gender%> </p> -->
       <br>
       <%= link_to "to the product", product_path(product), class: "btn btn-primary" %>
     </div>

     <div class="col-lg-1">
     </div>

     <div class="col-lg-6 photo">
      <p>photo</p>
     </div>


   <% end %>
 </div>
</div>


<br>

<!-- Leave it until the landing page has been created

<div>
<%= link_to "go to landing  page ", root_path %>
</div>

-->

app/views/products/index_bags.html.erb
<div class="container-fluid">
  <div class="jumbotron">
       <div class="container">
         <h1>Bags</h1>
         <p>SHINE, SHINE SHINE! </p>
         <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
       </div>
     </div>


  <div class="row">
  <% @products.each do |product| %>
    <div class="col-sm-6 col-md-4 card-prod">
      <div class="thumbnail-content">
        <% if product.picture_path %>
        <%= image_tag product.picture_path %>
        <% else %>
        <%= image_tag "http://lorempixel.com/1125/660/fashion/1/" %>
        <% end %>
        <p class="price"><%=product.price %></p>
      </div>
      <div class= "user-content">
        <div class="user-image">
          <%= image_tag "user2.jpg", class:"img-circle" %>
        </div>
        <div class="user-reviews">
            <div class="starrr" data-rating='4'></div>
        </div>

      </div>


      <div class="body-content">
        <h3><%= product.title %></h3>
        <p><%= product.description %></p>
        <p><%=product.brand %></p>

          <%= link_to "RENT", product_path(product), class: "btn btn-primary" %>
          <a href="#" class="btn btn-default" role="button">ORDER</a></p>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/products/index_jewelry.html.erb
<div class="container-fluid">
  <div class="jumbotron">
       <div class="container">
         <h1>Jewelry</h1>
         <p>SHINE, SHINE SHINE! </p>
         <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
       </div>
     </div>


  <div class="row">
  <% @products.each do |product| %>
    <div class="col-sm-6 col-md-4 card-prod">
      <div class="thumbnail-content">
        <% if product.picture_path %>
        <%= image_tag product.picture_path %>
        <% else %>
        <%= image_tag "http://lorempixel.com/1125/660/fashion/1/" %>
        <% end %>
        <p class="price"><%=product.price %></p>
      </div>
      <div class= "user-content">
        <div class="user-image">
          <%= image_tag "user2.jpg", class:"img-circle" %>
        </div>
        <div class="user-reviews">
            <div class="starrr" data-rating='4'></div>
        </div>

      </div>


      <div class="body-content">
        <h3><%= product.title %></h3>
        <p><%= product.description %></p>
        <p><%=product.brand %></p>

          <%= link_to "RENT", product_path(product), class: "btn btn-primary" %>
          <a href="#" class="btn btn-default" role="button">ORDER</a></p>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/products/index_watches.html.erb
  <div class="jumbotron jumbo-watches">
       <div class="container">
         <h1>Watches</h1>
         <p>Rent now ! </p>
       </div>
     </div>


<div class="container-fluid">


  <div class="row">
  <% @products.each do |product| %>
    <div class="col-sm-6 col-md-4 card-prod">
      <div class="thumbnail-content">
        <% if product.picture_path %>
        <%= image_tag product.picture_path %>
        <% else %>
        <%= image_tag "http://lorempixel.com/1125/660/fashion/1/" %>
        <% end %>
        <p class="price">$ <%=product.price %></p>
      </div>
      <div class= "user-content">
        <div class="user-image">
          <%= image_tag "user1.jpg", class:"img-circle" %>
        </div>
        <div class="user-reviews">
            <div class="starrr" data-rating='4'></div>
        </div>

      </div>


      <div class="body-content">
        <h3><%= product.title %></h3>

        <p><%=product.brand %></p>

          <%= link_to "RENT", product_path(product), class: "btn btn-primary pull-right" %>
      </div>
    </div>
  <% end %>
  </div>
</div>

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<footer>
    <div class="footer" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">
                    <h3> Find us at</h3>
                    <ul class="social">
                        <li> <a href="#"> <i class=" fa fa-facebook">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-twitter">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-google-plus">   </i> </a> </li>
                    </ul>
                </div>
            </div>
            <!--/.row-->
        </div>
        <!--/.container-->
    </div>
    <!--/.footer-->

    <div class="footer-bottom">
        <div class="container">
            <p class="pull-left"> Copyright © LorenzVillain. All right reserved. </p>
        </div>
    </div>
    <!--/.footer-bottom-->
</footer>

app/views/products/new.html.erb
<div class="container">
  <div style="margin-top: 75px;">
    <%= form_for @product do |f| %>

      <%= f.label :category %>
      <%= f.select :category, Product::CATEGORIES %>
      <%= f.label  :title %>
      <%= f.text_field :title%>
      <%= f.label :description %>
      <%= f.text_field :description %>
      <%= f.label  :brand %>
      <%= f.text_field :brand %>
      <%= f.label  :price %>
      <%= f.text_field :price %>
      <%= f.hidden_field :user_id, :value => current_user.id %>


     <%= f.button "Create" %>

    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container-fluid" id="fullscreen">


  <div class="bg-white">
    <div class="container body">
      <div class="row">
        <div class="col-sm-6">
          <div class="social-box">

            <h1><%= @product.title %></h1>
            <div class="image-product">
              <%= image_tag @product.picture_path, class:"img-responsive" %>
            </div>
          </div>
        </div>

        <div class="col-sm-6">
          <div class="block-info">
            <h4>  <%= @product.brand %> </h4>
            <h2>  <%= @product.description %></h2>

            <h3>  <%= @product.price %> € </h3>


            <%= form_for @order do |f| %>
            <p>Delivery date:</p>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker6'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <p>Return date:</p>
            <div class="form-group">
              <div class='input-group date' id='datetimepicker7'>
                  <input type='text' class="form-control" />
                  <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                  </span>
              </div>
          </div>
          <div class="theorder">
            <div class="order">
              <%= f.hidden_field :product_id, :value => @product.id%>
              <%= f.submit "Order", class: "btn btn-primary pull-right" %>
              <% end %>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
      <div class="row">
        <div class="col-sm-6">
          <div class="profile">
            <div class="profile-header">
              <div class="profile-image">
                  <%= image_tag "user1.jpg", class:"img-circle" %>
                </div>
                <div class="profile-username">
                  <h4>Teddy Java</h4>
                  <div class="starrr" data-rating='4'></div>
                </div>
              </div>
            <div class="profile-body">
              <p>28,graduated computer science, working as a freelancer web developer lives in Brussels Belgium</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<footer>
    <div class="footer" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">
                    <h3> Find us at</h3>
                    <ul class="social">
                        <li> <a href="#"> <i class=" fa fa-facebook">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-twitter">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-google-plus">   </i> </a> </li>
                    </ul>
                </div>
            </div>
            <!--/.row-->
        </div>
        <!--/.container-->
    </div>
    <!--/.footer-->

    <div class="footer-bottom">
        <div class="container">
            <p class="pull-left"> Copyright © LorenzVillain. All right reserved. </p>
        </div>
    </div>
    <!--/.footer-bottom-->
</footer>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker6').datetimepicker();
        $('#datetimepicker7').datetimepicker({
            useCurrent: false //Important! See issue #1075
        });
        $("#datetimepicker6").on("dp.change", function (e) {
            $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
        });
        $("#datetimepicker7").on("dp.change", function (e) {
            $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
        });
    });
</script>

app/views/products/view_add_product.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
    <div class="form_main">
                <h4 class="heading"><strong>Quick </strong> Contact <span></span></h4>
                <div class="form">
                  <%= form_for @product do |f| %>
                    <%= f.text_field :title, class: "test" %>
                    <%= f.button "Create" %>
                  <% end %>

                <form action="contact_send_mail.php" method="post" id="contactFrm" name="contactFrm">
                    <input type="text" required="" placeholder="Please input your Name">
                    <% @product.create%>
                    <input type="text" required="" placeholder="Please input your mobile No" value="" name="mob" class="txt">
                    <input type="text" required="" placeholder="Please input your Email" value="" name="email" class="txt">

                   <textarea placeholder="Your Message" name="mess" type="text" class="txt_3"></textarea>
                     <input type="submit" value="submit" name="submit" class="txt2">
                </form>
            </div>
            </div>
            </div>
  </div>
</div>

app/views/shared/_flashes.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<header>
  <div class="navWrapper" id="home">
    <div class=" clearfix">
      <h2 class="companyName">Prestige</h2>
      <nav class="mainNav clearfix">
        <ul>

          <li><%= link_to "Home", root_path %></li>

          <li class="dropdown smoothScroll">

            <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
            Profile <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <% if signed_in? %>
              <li class="menu-drop">
                <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
                <% end %>
              </li>
              <% end %>

              <li class="menu-drop">
                <%= link_to orders_path do %>
                <i class="fa fa-suitcase"></i>  <%= t ".profile", default: "Orders" %>
                <% end %>
              </li>
              <li class="menu-drop">
                <% if signed_in? %>
                <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Sign out" %>
                <% end %>
                <% else %>
                <%= link_to "Log in", new_user_session_path %>
                <% end %>
              </li>
            </ul>
          </li>

          <li><%= link_to "Become a Renter", new_product_path, class: "smoothScroll" %>


          </li>
          <li><a href="#contact" class="smoothScroll">Contact</a></li>

        </ul>
      </nav>
    </div><!-- end .innerWrapper -->
  </div><!-- end of .navWrapper -->
</header>